[package]
name = "github-api"
version = "0.1.0"
authors = ["k0pernicus <antonin.carette@gmail.com>"]

[dependencies]
hyper = "0.9"
serde = "0.8"
serde_derive = "0.8"
serde_macros = "0.8"
serde_json = "0.8"
